runtime: python312

env_variables:
  # API Provider Configuration
  API_PROVIDER: "openai"
  # Set your API keys in Cloud Console Environment Variables
  # OPENAI_API_KEY: "your-key-here"
  # GEMINI_API_KEY: "your-key-here"
  
  # Model Configuration
  DEFAULT_MODEL: "gpt-4o"
  SUMMARIZER_MODEL: "gpt-3.5-turbo"
  
  # Application Settings
  MAX_STEPS: "10"
  DEBUG_MODE: "False"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6 