steps:
  # Initialize git submodules
  - name: 'gcr.io/cloud-builders/git'
    args: ['submodule', 'update', '--init', '--recursive']
  
  # Create the SimpleAgent junction/symlink for Linux
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ln -sf SimpleAgent-Core/SimpleAgent SimpleAgent
        ls -la SimpleAgent/
  
  # Build and deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'simple-agent-websocket'
      - '--source'
      - '.'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'API_PROVIDER=openai,DEFAULT_MODEL=gpt-4o,SUMMARIZER_MODEL=gpt-3.5-turbo,MAX_STEPS=10,DEBUG_MODE=False'

options:
  logging: CLOUD_LOGGING_ONLY 